#!/usr/bin/env python
# Filename:                xkfootnix
# Description:             xkeys footpdeal into xdotool
# Supported Langauge(s):   Python 2.7.x
# Time-stamp:              <2012-02-05 08:52:59 fultonj> 
# -------------------------------------------------------
# usage:
# 
#   piehidtest | xkfootnix
#
# Q: How do I map the foot pedals to the keys I want?
# 
# A: Set the left, middle, and right variables below
#    to values supported by xdotool:
#    http://www.semicomplete.com/projects/xdotool/
# 
# See the README hosted on github for more information:
#
#   https://github.com/fultonj/xkfootnix
# -------------------------------------------------------
left = "alt"
middle = "ctrl"
right = "alt"
# -------------------------------------------------------
import sys
import os

while 1:
    try:
        input = sys.stdin.readline()
        if (input):
            if (len(input) > 10):
                if (input[7] == '1'):
                    if (input[10] == '2'):
                        cmd = "xdotool keydown " + left
                        os.popen(cmd).read()
                    elif (input[10] == '4'):
                        cmd = "xdotool keydown " + middle
                        os.popen(cmd).read()
                    elif (input[10] == '8'):
                        cmd = "xdotool keydown " + right
                        os.popen(cmd).read()
                    if (input[10] == '0'):
                        # release everything 
                        cmd = "xdotool keyup " + left
                        os.popen(cmd).read()
                        cmd = "xdotool keyup " + middle
                        os.popen(cmd).read()
                        cmd = "xdotool keyup " + right
                        os.popen(cmd).read()
    except:
        sys.exit()
